#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM ubuntu:20.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
    curl ca-certificates openssh-server \
    iproute2 iptables iputils-ping net-tools \
    # The following is used for Firecracker init
    init udev && \
    # The serial getty service hooks up the login prompt to the
    # kernel console at ttyS0 (where Firecracker connects its
    # serial console). Set to autologin to avoid login prompt.
    mkdir "/etc/systemd/system/serial-getty@ttyS0.service.d/" && \
    echo "[Service]\nExecStart=\nExecStart=-/sbin/agetty --autologin root --keep-baud 115200,38400,9600 %I $TERM\n" > /etc/systemd/system/serial-getty@ttyS0.service.d/autologin.conf && \
    passwd -d root && \
    rm -rf /var/lib/apt/lists/*

#-------------------------------------------------------------------------------
# 
# To build the image
# docker build -t focal-demo -f ./Dockerfile-focal-demo .
#

